apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-test-aspnet-deployment
  labels:
    app: container-test-aspnet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: container-test-aspnet
  template:
    metadata:
      labels:
        app: container-test-aspnet
    spec:
      containers:
      - name: container-test-aspnet
        image: srinivasan21nove/container_test_aspnet:v2
        ports:
        - containerPort: 80
